apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  labels:
    app.kubernetes.io/name: {{SERVICE_NAME}}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{SERVICE_NAME}}
  ports:
    - name: http
      port: {{PORT}}
      targetPort: http
      protocol: TCP
